apiVersion: apps/v1
kind: Deployment
metadata:
  name: taxapi-dep
  namespace: teste-granito
  labels:
    app: taxapi
spec:
  replicas: 1
  revisionHistoryLimit: 2
  selector:
    matchLabels:
      app: taxapi
      name: taxapi-dep
  strategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: taxapi
        name: taxapi-dep
    spec:
      containers:
        - name: taxapi
          resources:
            limits:
              cpu: 100m
              memory: 200Mi
            requests:
              cpu: 1m
              memory: 20Mi
          ports:
            - containerPort: 80
              protocol: TCP
              name: api
          livenessProbe:
            httpGet:
              path: /health
              port: 80
            initialDelaySeconds: 15
            periodSeconds: 60
          imagePullPolicy: Always
          image: "localhost:5000/taxapi:v1.1"
          env:
            - name: ASPNETCORE_ENV_HOST
              value: "Development"
            - name: TaxValue
              value: "0.01"

---
apiVersion: v1
kind: Service
metadata:
  name: taxapi-svc
  namespace: teste-granito
  labels:
    app: taxapi
spec:
  type: ClusterIP
  selector:
    app: taxapi
    name: taxapi-dep
  ports:
    - name: api
      protocol: TCP
      port: 80
      targetPort: 80
