apiVersion: apps/v1
kind: Deployment
metadata:
  name: calculatorapi-dep
  namespace: teste-granito
  labels:
    app: calculatorapi
spec:
  replicas: 1
  revisionHistoryLimit: 2
  selector:
    matchLabels:
      app: calculatorapi
      name: calculatorapi-dep
  strategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: calculatorapi
        name: calculatorapi-dep
    spec:
      containers:
        - name: calculatorapi
          resources:
            limits:
              cpu: 100m
              memory: 200Mi
            requests:
              cpu: 1m
              memory: 20Mi
          ports:
            - containerPort: 80
              protocol: TCP
              name: api
          livenessProbe:
            httpGet:
              path: /health
              port: 80
            initialDelaySeconds: 15
            periodSeconds: 60
          imagePullPolicy: Always
          image: "localhost:5000/calculatorapi:v1.1"
          env:
            - name: ASPNETCORE_ENV_HOST
              value: "Development"
            - name: CodeUrl
              value: "https://github.com/FabioTS/teste-granito"
            - name: TaxApiUrl
              value: "http://taxapi-svc.teste-granito:80/"
            - name: GetTaxPath
              value: "tax"

---
apiVersion: v1
kind: Service
metadata:
  name: calculatorapi-svc
  namespace: teste-granito
  labels:
    app: calculatorapi
spec:
  type: ClusterIP
  selector:
    app: calculatorapi
    name: calculatorapi-dep
  ports:
    - name: api
      protocol: TCP
      port: 80
      targetPort: 80
